name: Project Prometheus Engine

on:
  schedule:
    - cron: '0 0 * * *' # Production: Runs at midnight
  workflow_dispatch:      # Manual Trigger

permissions:
  contents: write

jobs:
  generate-sequence:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Initialize Python Core
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Graphic Dependencies
        run: |
          pip install Pillow

      - name: Engage Sequencer
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python .github/scripts/sequencer.py

      - name: Commit & Push Artifact
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(prometheus): update dna sequence [skip ci]"
          file_pattern: assets/dna.gif
